- name: Configurar rutas estaticas de la DMZ
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: "{{ item }}"
    state: present
  with_items:
    - 'up ip -4 route add 190.6.78.48/29 via 192.168.40.1'
    - 'up ip -4 route add 152.206.0.0/15 via 192.168.40.2'
    - 'up ip -4 route add 169.158.0.0/16 via 192.168.40.2'
    - 'up ip -4 route add 181.225.224.0/19 via 192.168.40.2'
    - 'up ip -4 route add 190.6.64.0/20 via 192.168.40.2'
    - 'up ip -4 route add 190.6.80.0/20 via 192.168.40.2'
    - 'up ip -4 route add 190.15.144.0/20 via 192.168.40.2'
    - 'up ip -4 route add 190.92.112.0/20 via 192.168.40.2'
    - 'up ip -4 route add 190.107.0.0/20 via 192.168.40.2'
    - 'up ip -4 route add 196.1.112.0/24 via 192.168.40.2'
    - 'up ip -4 route add 196.1.135.0/24 via 192.168.40.2'
    - 'up ip -4 route add 196.3.152.0/24 via 192.168.40.2'
    - 'up ip -4 route add 200.0.16.0/24 via 192.168.40.2'
    - 'up ip -4 route add 200.0.24.0/22 via 192.168.40.2'
    - 'up ip -4 route add 200.5.12.0/22 via 192.168.40.2'
    - 'up ip -4 route add 200.13.144.0/21 via 192.168.40.2'
    - 'up ip -4 route add 200.14.48.0/21 via 192.168.40.2'
    - 'up ip -4 route add 200.55.128.0/19 via 192.168.40.2'
    - 'up ip -4 route add 200.55.160.0/20 via 192.168.40.2'
    - 'up ip -4 route add 200.55.176.0/20 via 192.168.40.2'
    - 'up ip -4 route add 201.220.192.0/20 via 192.168.40.2'
    - 'up ip -4 route add 201.220.208.0/20 via 192.168.40.2'
    - 'up ip -4 route add 172.32.0.0/16 via 192.168.40.3'
    - 'up ip -4 route add 10.16.0.0/17 via 192.168.40.4'
  notify: restart_systemd_networkd
