- name: Configurar rutas estaticas del router VPN
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: "{{ item }}"
    state: present
  with_items:
    - 'up ip -4 route add 172.32.20.0/24 via 192.168.26.1'
  notify: restart_systemd_networkd
