all:
  children:
    dpvhab:
      hosts:
        fw1:
          ansible_host: 192.168.40.3
        fw2:
          ansible_host: 192.168.40.1
        fw3:
          ansible_host: 192.168.40.2
        ns1:
          ansible_host: 192.168.40.10
        mx1:
          ansible_host: 192.168.40.12
        px1:
          ansible_host: 192.168.40.30
        r1:
          ansible_host: 172.32.16.1
        r2:
          ansible_host: 190.6.78.49
        r3:
          ansible_host: 190.6.67.1
    dmz:
      hosts:
        ns1:
        mx1:
        px1:
    firewalls:
      hosts:
        fw1:
        fw2:
        fw3:
    routers:
      hosts:
        r1:
        r2:
        r3:
