all:
  children:
    dpvhab:
      hosts:
        router-www:
          ansible_host: 190.6.78.49
        router-nac:
          ansible_host: 190.6.67.1
        router-vpn:
          ansible_host: 172.32.16.1
        firewall-www:
          ansible_host: 192.168.40.1
        firewall-nac:
          ansible_host: 192.168.40.2
        firewall-vpn:
          ansible_host: 192.168.40.3
        firewall-lan:
          ansible_host: 192.168.40.4
        ns:
          ansible_host: 192.168.40.10
        px:
          ansible_host: 192.168.40.12
        mx:
          ansible_host: 192.168.40.14
        repo:
          ansible_host: 192.168.40.16
        adm:
          ansible_host: 192.168.40.18
    routers:
      hosts:
        router-www:
        router-nac:
        router-vpn:
    firewalls:
      hosts:
        firewall-www:
        firewall-nac:
        firewall-vpn:
        firewall-lan:
    dmz:
      hosts:
        ns:
        px:
        mx:
        repo:
        adm:

